Add script fix-program-events-user
EyeSeeTea/organisationUnit-User-Assigment pull request #36
Opened 2017-03-07 11:24 UTC by tokland

2017-03-08 00:04 UTC, adrianq requested changes
@tokland Incredible work! It took me a while to understand some ES6 code as I am not familiar with it. Some minor changes requested. Can you also change the name of the script (and the description and methods) to 'user-ProgramAttribute-assignment'? Once these changes are done I will ask @josemp10 to test it and double check the dhis2 specific stuff makes sense. Thanks!

2017-03-08 00:04 UTC, adrianq commented on src/scripts/fix-program-events-user/.eslintrc.json
> +{
@tokland Awesome! Don't know too much about this. I would like to discuss a bit about this with you on Thursday.

2017-03-08 00:04 UTC, adrianq commented on src/scripts/fix-program-events-user/config.json
> +        "url": "http://localhost:8080/api/24",
@tokland My fault, sorry, but it was supposed to be targeting 2.25. Can you please update and test it for 2.25?

2017-03-08 00:04 UTC, adrianq commented on src/scripts/fix-program-events-user/index.js
> +            return this.request("events/" + eventId, {method: "PUT", body: body});
@tokland I guess what I told you about sending the whole date structure again is not needed, right? We can only send the bit that is changing, correct?

2017-03-08 00:04 UTC, adrianq commented on src/scripts/fix-program-events-user/package.json
> +  "author": "Arnau Sanchez",
@tokland I know we have the name of the developers in some scripts but we have decided to set the author to 'EyeSeeTea Team' (for instance in Data Dictionary). Can you please change it accordingly?

2017-03-08 06:46 UTC, tokland commented on src/scripts/fix-program-events-user/index.js
> +            return this.request("events/" + eventId, {method: "PUT", body: body});
This is sending the whole event, `_.defaults(obj1, obj2)` merges obj1 and obj2, you (or Jose) were right, if some attribute is not sent, it's removed from the DB event. That's also true for the dataValues entries, that's why its timestamp is updated.

2017-03-08 06:58 UTC, tokland commented
I forgot, this is the debug output with `--fromDate=-100`. There are quite a lot of users nor found in the category options:

[script-output.txt](https://github.com/EyeSeeTea/organisationUnit-User-Assigment/files/826867/script-output.txt)

2017-03-08 08:41 UTC, adrianq commented on src/scripts/fix-program-events-user/index.js
> +            return this.request("events/" + eventId, {method: "PUT", body: body});
Yep, you are right. I didn't realise about the second parameter

2017-03-08 08:42 UTC, adrianq approved these changes

2017-03-08 08:49 UTC, adrianq commented
@tokland Thank you very much for the changes. Everything looks good to me.

@josemp10 I have requested a review on your side about this PR. Please give it a try. If everything is working fine approve the review and I will merge the code. Otherwise, request any change. See also some notes about the PR [here](https://github.com/EyeSeeTea/organisationUnit-User-Assigment/issues/34). Note there is also a question for you in the issue. Drop me a line if you have any doubt about this. Thanks!

2017-03-27 13:00 UTC, josemp10 commented
I have tested the script in a development environment, and everything seems
to be correct. Thanks guys!

On Wed, Mar 8, 2017 at 9:49 AM, Adrian Quintana <notifications@github.com>
wrote:

> @tokland <https://github.com/tokland> Thank you very much for the
> changes. Everything looks good to me.
>
> @josemp10 <https://github.com/josemp10> I have requested a review on your
> side about this PR. Please give it a try. If everything is working fine
> approve the review and I will merge the code. Otherwise, request any
> change. See also some notes about the PR here
> <https://github.com/EyeSeeTea/organisationUnit-User-Assigment/issues/34>.
> Note there is also a question for you in the issue. Drop me a line if you
> have any doubt about this. Thanks!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/EyeSeeTea/organisationUnit-User-Assigment/pull/36#issuecomment-284982802>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AD9HZ-P6jgq3yQKmojmoadkMvDMeG-TLks5rjmuzgaJpZM4MVW75>
> .
>

2017-03-27 17:23 UTC, merged